# Generated by Django 5.2.4 on 2025-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_purchase_type_sale_type_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='type',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='ee', max_length=50),
            preserve_default=False,
        ),
    ]
