# Generated by Django 5.2.4 on 2025-07-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_purchase_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_by',
        ),
    ]
