# Generated by Django 5.2.4 on 2025-07-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_product_total_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
