# Generated by Django 5.2.4 on 2025-07-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_product_total_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_cost_value',
        ),
    ]
