# Generated by Django 5.2.4 on 2025-07-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_product_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
