# Generated by Django 5.2.4 on 2025-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_product_current_stock_alter_product_total_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='total_cost_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
