# Generated by Django 5.2.4 on 2025-07-14 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_bc_ds9c_np7a_number8'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bc',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bc211', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ds9c',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='np7a',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='np7a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='number8',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number', to=settings.AUTH_USER_MODEL),
        ),
    ]
