# Generated by Django 5.2.4 on 2025-07-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_bc_current_stock_bc_total_cost_value_bc_total_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcpurchase',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.type'),
        ),
    ]
