# Generated by Django 5.0 on 2025-07-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_nsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.number8'),
        ),
    ]
