# Generated by Django 5.2.4 on 2025-07-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_n7sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ds9c',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
